foreground         #c0c4ca
background         #03142D
background_opacity 1.0
cursor             #c0c4ca

active_tab_foreground     #03142D
active_tab_background     #c0c4ca
inactive_tab_foreground   #c0c4ca
inactive_tab_background   #03142D

active_border_color   #c0c4ca
inactive_border_color #03142D
bell_border_color     #b1845a

color0       #03142D
color8       #5e6672
color1       #b1845a
color9       #ECB079
color2       #175268
color10      #1F6E8B
color3       #465466
color11      #5E7089
color4       #216f7d
color12      #2D94A7
color5       #437b84
color13      #5AA5B1
color6       #428d96
color14      #58BDC8
color7       #91959b
color15      #c0c4ca
