#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                

# Core Colors
background            #0d141c
foreground            #dde3ee
selection_foreground  #9bcaff
selection_background  #003256
cursor                #9bcaff
cursor_text_color     #0d141c

# Regular Colors
color0  #0d141c               
color1  #ffb4ab                 
color2  #9bcaff               
color3  #bfc2fa              
color4  #d0e4ff  
color5  #d8e2ff
color6  #b8c6ea             
color7  #dde3ee            

# Bright Colors
color8  #333a42         
color9  #ffb4ab                  
color10 #9bcaff                
color11 #bfc2fa               
color12 #d0e4ff   
color13 #d8e2ff 
color14 #b8c6ea              
color15 #dde3ee             