#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┓┏┓┳┏┳┓┏┳┓┓┏
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┫ ┃ ┃  ┃ ┗┫
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┛┗┛┻ ┻  ┻ ┗┛
#                                

# Core Colors
background            #1a1112
foreground            #f0dedf
selection_foreground  #ffb2b8
selection_background  #561d25
cursor                #ffb2b8
cursor_text_color     #1a1112

# Regular Colors
color0  #1a1112               
color1  #ffb4ab                 
color2  #ffb2b8               
color3  #e7c08e              
color4  #ffdadb  
color5  #ffdadb
color6  #e6bdbe             
color7  #f0dedf            

# Bright Colors
color8  #413737         
color9  #ffb4ab                  
color10 #ffb2b8                
color11 #e7c08e               
color12 #ffdadb   
color13 #ffdadb 
color14 #e6bdbe              
color15 #f0dedf             