$browser = google-chrome-stable
$terminal = kitty
$gui_editor = code
$menu = ~/.config/rofi/launchers/type-1/launcher.sh
$file_manager = kitty ranger
$gui_file_manager = dolphin
$lockscreen = hyprlock
