layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.0, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar

layerrule = blur on, match:namespace logout_dialog
layerrule = animation popin 95%, match:namespace logout_dialog

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.0, match:namespace rofi
layerrule = animation popin 95%, match:namespace rofi

layerrule = animation popin 95%, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.0, match:namespace swaync-control-center
layerrule = ignore_alpha 0.0, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

layerrule = no_anim on, match:namespace hyprpicker
layerrule = no_anim on, match:namespace selection
