layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blurpopups, waybar

layerrule = blur, logout_dialog
layerrule = animation popin 95%, logout_dialog

layerrule = blur, rofi
layerrule = ignorezero, rofi
layerrule = animation popin 95%, rofi

layerrule = animation popin 95%, swaync-control-center
layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

layerrule = noanim, hyprpicker
layerrule = noanim, selection
