# Assign applications to workspaces
windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 2, match:class ^(code)$
windowrule = workspace 3, match:class ^(brave-browser)$
windowrule = workspace 4, match:class ^(Notion)$
windowrule = workspace 5, match:class ^(org.kde.dolphin)$
windowrule = workspace 6, match:class ^(org.telegram.desktop)$
windowrule = workspace 6, match:class ^(discord)$
windowrule = workspace 7, match:class ^(Apple Music)$

# Windows opacity
windowrule = opacity 0.8, match:class ^(code-url-handler)$
windowrule = opacity 0.8, match:class ^(jetbrains-pycharm)$
windowrule = opacity 0.8, match:initial_title ^(Spotify Free)$
windowrule = opacity 0.8, match:class ^(org.telegram.desktop)$
windowrule = opacity 0.8, match:class ^(com.ayugram.desktop)$
windowrule = opacity 0.8, match:class ^(org.gnome.Nautilus)$
windowrule = opacity 0.8, match:class ^(SWT)$
windowrule = opacity 0.8, match:class ^(Simplenote)$
windowrule = opacity 0.8, match:class ^(Postman)$
windowrule = opacity 0.8, match:class ^(Insomnia)$
windowrule = opacity 0.8, match:class ^(jadx-gui)$
windowrule = opacity 0.8, match:class ^(localsend_app)$
windowrule = opacity 0.8, match:class ^(obsidian)$

# Windows tiling (default - windows tile by default)

# Windows floating
windowrule = float on, match:class ^(SWT)$
windowrule = float on, match:class ^(Genymotion Player)$
windowrule = float on, match:class ^(scrcpy)$
# windowrule = float on, match:class ^(Chromium-browser)$
# windowrule = float on, match:class ^(Chromium)$
windowrule = float on, match:class ^(wlogout)$
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, match:title ^(File Operation Progress)$
windowrule = float on, match:title ^(win)$
windowrule = float on, match:title ^(Java)$
windowrule = center on, match:float true, match:title ^(Java)$
windowrule = center on, match:float true, match:title ^(splash)$
windowrule = no_focus on, match:float true, match:class ^jetbrains-.*, match:title ^win\d+$
windowrule = no_focus off, match:float true, match:class ^jetbrains-toolbox$, match:title ^win\d+$

# Prevent suspend when a fullscreen app is open
windowrule = idle_inhibit fullscreen, match:class .*
windowrule = idle_inhibit fullscreen, match:fullscreen true

windowrule = no_max_size on, match:class .*

windowrule = float on, match:class ^(clipse)$
windowrule = size 800 652, match:class ^(clipse)$
windowrule = stay_focused on, match:class ^(clipse)$